config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  resources :events, only: [:index, :new, :create, :show]
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :attendance, optional: true
    belongs_to :user, optional: true

    after_create :new_event_send
      
    def new_event_send
        IntendanceMailer.new_event_email(self).deliver_now
    end
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    has_many :users, through: :attendances
    has_many :attendances

    validates :start_date, presence: true
    validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true
    validates :location, presence: true      
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :events, through: :attendances


    after_create :welcome_send
      
    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :alert
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: [:show, :new, :create]

    def index 
        @events = Event.all
    end

    def new
        @event = Event.new
    end
    
    def create
        @event = Event.create(post_params)
        @event.user = current_user
        
        if @event.save
          puts "saved"
          redirect_to events_path, :notice => 'Evenement créé'
        else
          puts "ça n'a pas fonctionne,essaie encore"
          puts @event.errors.messages
          render 'new'
        end
    
    end

    def show 
        @event = params[:id]
        @event_id = Event.find(params[:id])
    end

    private

    def post_params
      params.permit(:title, :start_date, :description, :duration, :price, :location)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :only_see_own_page, only: [:show]

    def show 
        @user = User.find(params[:id])
        @events = Event.all
    end

    private

    def only_see_own_page
        @user = User.find(params[:id])
      
        if current_user != @user
          redirect_to root_path, notice: "Sorry, but you are only allowed to view your own profile page."
        end
    end
      

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1> Bienvenue sur The Event Project ! </h1> 

<div class ="container" style="padding-top: 5rem;">

<br>
<%= button_to "Creer un Event", new_event_path, :method => "get", class:'btn btn-success' %>
<br>

<div class="card-columns">
  <% @events.each do |event|%>
    <div class="card" style="max-width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"> Title : <%= event.title %></h5> 
        <p class="card-text"><small class="text-muted"> Author <%= event.user.first_name %></small></p>
        <%= link_to "voir l'event", event_path(event.id), class:"btn btn-primary" %>
        <a href="<%=  event_path(event.id) %>" class="btn btn-danger"  data-confirm="Etes-vous surs de vouloir supprimer le event ?" data-method="DELETE"> Supprimer </a>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1> Créer un nouvel événement ! </h1>


<!-- ... -->

<form>
  <div class="form-group">

<%= form_tag events_path(action: 'create'), method: "post" do %>

  <%= label_tag 'Titre' %>
  <%= text_field_tag 'title', @event.title %>
  <br /> <br />

  <%= label_tag 'Quand' %>
  <%= datetime_field_tag 'start_date', @event.start_date %>
  <br /> <br />

  <%= label_tag 'Description' %>
  <%= text_area_tag 'description', @event.description %>
  <br /> <br />

  <%= label_tag 'Durée' %>
  <%= text_field_tag 'duration', @event.duration %>
  <br /> <br />
  
  <%= label_tag 'Prix pour 1 entrée' %>
  <%= text_field_tag 'price', @event.price %>
  <br /> <br />

  <%= label_tag 'Où ça ?' %>
  <%= text_field_tag 'location', @event.location %>
  <br /> <br />

  <%= submit_tag "Create Gossip", class: 'btn btn-primary' %>

<% end %>

</div>
</form>

<!-- ... -->

app/views/events/show.html.erb
<div class="card">
    <div class="card-header">
         Event numéro <%= @event %>: 
    </div>

    <div class="card-body">
        <h6 class="card-title"> <U>le titre de l'Event est:</U> <%=@event_id.title %> </h6>
            <h7> l'auteur est: <%= link_to "#{@event_id.user.email}", user_path%></h7>
            <p> cette event a été crée le: <%=@event_id.created_at %> </p> </br>
            <p><U>Contenu de l'event:</U> </p> </br>
            <p> <%=@event_id.description %> </p> </br>
            <a href="<%=  event_path(@event) %>" class="btn btn-danger"  data-confirm="Etes-vous sur ?" data-method="DELETE"> Supprimer </a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "EventBrite", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Créer un événement", new_event_path, class: "nav-link" %>
          </li>

          <% if user_signed_in? == false %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Inscription / Conenxion
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Inscription", new_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Connexion", new_user_session_path, class: "dropdown-item" %>
              </div>
            </div>
          <% else %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Mon Profil / Déconnexion
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Mon profil", user_path(current_user.id), class: "dropdown-item" %>
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </div>
            </div>
          <% end %>

          
        </ul>
      </div> 
    </nav>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1> 

<p> T'es infos
  <li> Ton prénom : <%= @user.first_name %> </li>
  <li> Ton nom de famille : <%= @user.last_name %> </li>
  <li> Ta description: <%= @user.description %> </li>
  <li> Ton email : <%= @user.email %> </li>
</p>

<div class="card-columns">
<% @events.each do |event|%>
    <% if event.user_id == @user.id %>
  <div class="card" style="max-width: 18rem;">
    <div class="card-body">
    
      <h5 class="card-title"> Title : <%= event.title %></h5> 
      <p class="card-text"><small class="text-muted"> Author <%= event.user.first_name %></small></p>
      <%= link_to "voir l'event", event_path(event.id), class:"btn btn-primary" %>
    
    </div>
  </div>
  <% end %>
<% end %>
</div>